[book]
authors = ["Dmdv"]
language = "en"
multilingual = false
src = "docs"
title = "AWP (Async Worker Pool & Ultra-Low-Latency HFT Engine)"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/Dmdv/async-worker-pool_zig"
